name: DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: SonarQube Scan
      run: mvn sonar:sonar \
        -Dsonar.projectKey=demo \
        -Dsonar.host.url=http://54.174.215.167:9000 \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Upload to Nexus
      run: mvn deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    - name: Deploy to Tomcat
      run: |
        curl -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASS }} \
        -T target/*.war \
        "http://54.174.215.167:8080/manager/text/deploy?path=/app&update=true"
